// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB99H1M4xBnKnyZWbKQGCcCJHSCP0YaIiY',
    appId: '1:431681252175:web:8844ebffbc990203e3733a',
    messagingSenderId: '431681252175',
    projectId: 'app-learning-2026',
    authDomain: 'app-learning-2026.firebaseapp.com',
    storageBucket: 'app-learning-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALxI3kpbxRzMKdh5ukq2AoRdWOXdgp2zg',
    appId: '1:431681252175:android:8a3ef7bf2d2e5fd8e3733a',
    messagingSenderId: '431681252175',
    projectId: 'app-learning-2026',
    storageBucket: 'app-learning-2026.firebasestorage.app',
  );
}
